### ISSUE TITLE
Column options menu partially hidden

### ISSUE THREAD

**Issue by kortemik** [teragrep/ajs_01#107]
ID <164>
Reporter <@StrongestNumber9>

[![Peek_2022-04-20_09-55.webm](/com-teragrep/ajs_01/issue/raw/files/a38d53fdbc81ba092cc8693c456d601e429d5afc8b8e372818f6d6190427d3ec-Peek_2022-04-20_09-55.webm)](/com-teragrep/ajs_01/issue/raw/files/a38d53fdbc81ba092cc8693c456d601e429d5afc8b8e372818f6d6190427d3ec-Peek_2022-04-20_09-55.webm)

As a side note I think it could benefit from some divisors between option groups

**Comment by ronja-ui** [comment]
This will be fixed when the pivot table has been replaced with datatables
