### ISSUE TITLE
Search from notebooks doesn't give the actual amount of matches

### ISSUE THREAD

**Issue by kortemik** [teragrep/ajs_01#149]
ID <231>
Reporter <@ronja-ui>

For some reason search from notebooks feature in navbar doesn't show the actual amount of search matches on the results page. 

It also gives: 'Error: ui-ace cannot use an object or an array as a model'

Investigate and fix this before the community release.

**Comment by ronja-ui** [comment]
This feature won't be fixed, see issue #285
