### ISSUE TITLE
You can add multiple duplicated fields in graph values section breaking the UI

### ISSUE THREAD

**Issue by kortemik** [teragrep/ajs_01#172]
ID <274>
Reporter <@StrongestNumber9>

[![Peek_2022-11-07_10-00.webm](/com-teragrep/ajs_01/issue/raw/files/c375ac5ad9ce3d3a89add5e3b9e7872ffc58e268953d28e42f5d58fe67120d5d-Peek_2022-11-07_10-00.webm)](/com-teragrep/ajs_01/issue/raw/files/c375ac5ad9ce3d3a89add5e3b9e7872ffc58e268953d28e42f5d58fe67120d5d-Peek_2022-11-07_10-00.webm)

**Comment by BVVLD** [comment]
Should be fixed in new drag&drop component
