### ISSUE TITLE
Unicode characters are "????" in the table headers

### ISSUE THREAD

**Issue by kortemik** [teragrep/ajs_01#176]
ID <279>
Reporter <@StrongestNumber9>

```sh
%dpl
index=crud_small | eval こんにちは="こんにちは"
```

[![Screenshot_20221123_121650.png](/com-teragrep/ajs_01/issue/raw/files/d23a6d85bea31881c8792a06fd7812f42d8ab868c4e6e5c05dec3c33dee29a1c-Screenshot_20221123_121650.png)](/com-teragrep/ajs_01/issue/raw/files/d23a6d85bea31881c8792a06fd7812f42d8ab868c4e6e5c05dec3c33dee29a1c-Screenshot_20221123_121650.png)

**Comment by BVVLD** [comment]
The issue seems to be resolved. Currently, all unicode characters are displayed properly.
