### ISSUE TITLE
Hint the user that index=* is the worst search ever

### ISSUE THREAD

**Issue by kortemik** [teragrep/ajs_01#184]
ID <294>
Reporter <@ronja-ui>

Currently, the UI doesn't hint in any way that it obviously takes time if the user does index=* search in DPL. 

Add some kind of message (maybe a toast message?) whenever the user is trying to do index=* search which fetches too much results (which therefore takes extra time).

**Comment by BVVLD** [comment]
the feature was successfully implemented before the release 8.0.0
Currently, if user writes query "index=*", it will create a notification above the code editor.
