### ISSUE TITLE
Source fontawesome from npm packages

### ISSUE THREAD

**Issue by ronja-ui** [teragrep/ajs_01#199]
Current self-hosted fontawesome is

* too big and heavy
* hard to maintain

so it's better to turn it to be a dependency. 

See more at 

* https://fontawesome.com/docs/web/setup/packages
* https://www.npmjs.com/package/@fortawesome/fontawesome-free

**Comment by BVVLD** [comment]
Fontawesome moved from self-hosted to the @fortawesome/fontawesome-free dependency.
