### ISSUE TITLE
Replace outdated angular-dragdrop with new similar library

### ISSUE THREAD

**Issue by BVVLD** [teragrep/ajs_01#205]

**Comment by BVVLD** [comment]
The angular-dragdrop is a rather outdated and badly documented library. Version implemented in zeppelin-web: 1.0.11. It is not mentioned in NPM version history. Presumably 8 years old. Latest: 1.0.13 and it is 7 years old.
We need something better than that.

**Comment by ronja-ui** [comment]
First re-design option
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1VEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ae7490a526fda48c1bd67156b80acf6b3657339/Screenshot%202023-10-04%20at%2014-55-06%20Teragrep.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1lEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0faa7f26d2ee1cf9f3e70e4f7c8f1b8d9ddaf6f/Screenshot%202023-10-04%20at%2014-56-19%20Teragrep.png)

**Comment by ronja-ui** [comment]
Second re-design option

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek1EQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--516f55eec2bcb11cd6eaaed6356561c39407b563/Screenshot%202023-10-04%20at%2015-23-20%20Teragrep.png)

**Comment by ronja-ui** [comment]
A bug found
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWh0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b68ccfded5d0267fd09947e5d7834d3a6ce8d35b/Peek%202023-10-25%2012-39.webm)

**Comment by BVVLD** [comment]
The bug should have been fixed, unit tests created and feature is considered done for now
