### ISSUE TITLE
Improve UX around commit/file saving

### ISSUE THREAD

**Issue by ronja-ui** [teragrep/ajs_01#206]
Remove the modal which appears when a new save is made. Saving should be as easy as possible so the modal is an unnecessary step. 

Also, prevent the user to make a new save if there's no name for the save. Currently you can go through the whole process without getting any message that there's no name for the save even if untitled saves are not permitted.

**Comment by BVVLD** [comment]
Now saving dropdown is handling all the interactions itself. If input is empty, dropdown will show an alert. On any other input the dropdown will send a websocket call with message and note ID and will close itself.
Code, related to the modal itself was removed.
The new feature has tests, that ensures correct error handling and websocket calls.
