### ISSUE TITLE
Limit interpreter restart's drop-down menu width

### ISSUE THREAD

**Issue by ronja-ui** [teragrep/ajs_01#219]
The drop-down menu is too wide, limit the width to improve UX.

To limit the width, the html structure might need rewriting, since repeated interpreter sub groups are inlined no matter what you do via CSS.

**Comment by kortemik** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE43QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7175fd2a19a59f6f79f0d9e181b222e20c8e54d2/inter.png)
