### ISSUE TITLE
Set cookie SameSite attributes properly

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/ajs_01#237]
**Description**

Browser tells me this:

> Cookie “darkMode” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
 
**Use case or motivation behind the feature request**

Being up to standards and having explicitly set attributes is a good idea
 
**Related issues**

 
**Additional context**

**Comment by BVVLD** [comment]
The issue is resolved as a part of the cookie management refactoring. All cookies will get a "SameSite=Strict;" parameter, which should prevent cross-site transfer. However, sources claims this to be not a completely safe measurement, therefore no sensitive data should be stored.

**Comment by ronja-ui** [comment]
pr merged
