### ISSUE TITLE
After AJS_01 8.0.0 upgrade login page does not work

### ISSUE THREAD

**Issue by nwellingk** [teragrep/ajs_01#263]
**Describe the bug**
AJS_01 8.0.0 was upgraded to, ZEP_01 restarted, login page does not work through proxy or with direct link.

**Expected behavior**
Login page should work.

**How to reproduce**
Occurs every time at customer's environment.

**Screenshots**
Not available

**Software version**
AJS_01: 8.0.0
ZEP_01: 2.0.2

**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 

**Additional context**
Firefox responds {"status":"METHOD_NOT_ALLOWED"}

**Comment by BVVLD** [comment]
The issue was connected to the configuration of "shiro.ini" file, which should be resolved by now.

**Comment by StrongestNumber9** [comment]
Just as a note, it was internal commit `77f45fae31920919f3c4c2a5af9aa363a755f8e3` that added `ShiroFilter` to `src/WEB-INF/web.xml` to enable make SSO/OIDC work properly. 

Issue can be solved by adding `/ = anon` before `/** = authc` line in `shiro.ini`

```
/ = anon
/** = authc
```
