### ISSUE TITLE
Hide graph view selector and graph options in report mode

### ISSUE THREAD

**Issue by ronja-ui** [teragrep/ajs_01#269]
**Description**
Graph view selector and graph options shouldn't be visible in the report mode. The report mode is only for showing results and users shouldn't be able to alter those.

**Comment by ronja-ui** [comment]
Users who have rights to only run or read a notebook can't switch graph view or alter graph options. However, these controls are not hidden for these users either. This causes situation where the login modal shows up after an already logged in user clicks one of these controls.

**Comment by BVVLD** [comment]
Partial fix for the problem:
Currently, if the view mode is "report" that should hide the controls. However, if user has only read or run permissions, they still will see the controls. That should be fixed as well.
