### ISSUE TITLE
Resizing paragraph output resizes it to wrong size and duplicates content

### ISSUE THREAD

**Issue by kortemik** [teragrep/ajs_01#52]
ID <56>
Reporter <@StrongestNumber9>

It also survives refresh. You have to resize it to the double of your intended size to make it look normal

[![Peek_2022-01-19_15-23.webm](/com-teragrep/ajs_01/issue/raw/files/c935c85eda4517e0062db2d68cdae9b0df2e3d93c3b4c578d06d8a35d0225bf0-Peek_2022-01-19_15-23.webm)](/com-teragrep/ajs_01/issue/raw/files/c935c85eda4517e0062db2d68cdae9b0df2e3d93c3b4c578d06d8a35d0225bf0-Peek_2022-01-19_15-23.webm)

**Comment by ronja-ui** [comment]
fixed since paragraph resizing is limited to width selection
