### ISSUE TITLE
numeric table sorts based on strings not numbers

### ISSUE THREAD

**Issue by kortemik** [teragrep/ajs_01#65]
ID <89>
Reporter <@kortemik>

consider asc sorting
```
1
7
9
10
```

numeric table sorts them
```
1
10
7
9
```

**Comment by BVVLD** [comment]
with the new table, there is no feature to choose the data type manually. It should be implemented in later updates

**Comment by ronja-ui** [comment]
The issue has been solved on DPL side. No further actions needed on UI side.
